# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.proto import face_pb2 as api_dot_proto_dot_face__pb2


class APIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchFace = channel.unary_unary(
                '/api.product.pft.v1.face.API/SearchFace',
                request_serializer=api_dot_proto_dot_face__pb2.SearchFaceReq.SerializeToString,
                response_deserializer=api_dot_proto_dot_face__pb2.SearchFaceReply.FromString,
                )


class APIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchFace': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchFace,
                    request_deserializer=api_dot_proto_dot_face__pb2.SearchFaceReq.FromString,
                    response_serializer=api_dot_proto_dot_face__pb2.SearchFaceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.product.pft.v1.face.API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class API(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.product.pft.v1.face.API/SearchFace',
            api_dot_proto_dot_face__pb2.SearchFaceReq.SerializeToString,
            api_dot_proto_dot_face__pb2.SearchFaceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
