# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/proto/face.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pi/proto/face.proto\x12\x17\x61pi.product.pft.v1.face\"\x1e\n\rSearchFaceReq\x12\r\n\x05\x66\x65\x61ts\x18\x01 \x03(\x02\"%\n\x0fSearchFaceReply\x12\x12\n\nstudent_id\x18\x02 \x01(\t2g\n\x03\x41PI\x12`\n\nSearchFace\x12&.api.product.pft.v1.face.SearchFaceReq\x1a(.api.product.pft.v1.face.SearchFaceReply\"\x00\x62\x06proto3')



_SEARCHFACEREQ = DESCRIPTOR.message_types_by_name['SearchFaceReq']
_SEARCHFACEREPLY = DESCRIPTOR.message_types_by_name['SearchFaceReply']
SearchFaceReq = _reflection.GeneratedProtocolMessageType('SearchFaceReq', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHFACEREQ,
  '__module__' : 'api.proto.face_pb2'
  # @@protoc_insertion_point(class_scope:api.product.pft.v1.face.SearchFaceReq)
  })
_sym_db.RegisterMessage(SearchFaceReq)

SearchFaceReply = _reflection.GeneratedProtocolMessageType('SearchFaceReply', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHFACEREPLY,
  '__module__' : 'api.proto.face_pb2'
  # @@protoc_insertion_point(class_scope:api.product.pft.v1.face.SearchFaceReply)
  })
_sym_db.RegisterMessage(SearchFaceReply)

_API = DESCRIPTOR.services_by_name['API']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCHFACEREQ._serialized_start=49
  _SEARCHFACEREQ._serialized_end=79
  _SEARCHFACEREPLY._serialized_start=81
  _SEARCHFACEREPLY._serialized_end=118
  _API._serialized_start=120
  _API._serialized_end=223
# @@protoc_insertion_point(module_scope)
